version: '3.1'

services:
  # eos-api:
  #     build:
  #         context: ./
  #         dockerfile: Dockerfile
  #     volumes:
  #         - '.:/usr/src/'
  #     ports:
  #         - '3333:3333'
  #     environment:
  #         - CHOKIDAR_USEPOLLING=1
  #     networks:
  #         - app-network
  #     depends_on:
  #         - db
  #     tty: true

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
    ports:
      - 5432:5432
    networks:
      - app-network

  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}_test
      POSTGRES_USER: ${PG_USER}
    ports:
      - 5433:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
